#!/bin/bash
################################################################################
# Bloom Website - Font Subsetting Script
# Reduces font file sizes by including only necessary glyphs
#
# Requirements:
#   - Python 3.7+
#   - fonttools: pip install fonttools brotli
#
# Usage:
#   ./scripts/subset-fonts.sh
#   npm run optimize:fonts
################################################################################

set -e

# Configuration
FONT_DIR="./src/assets/fonts"
OUTPUT_DIR="./public/fonts"

# Glyphset: Basic Latin + Latin-1 Supplement
UNICODES="U+0020-007E,U+00A0-00FF"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

################################################################################
# Functions
################################################################################

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

check_dependencies() {
    log_info "Checking dependencies..."

    if ! command -v python3 &> /dev/null; then
        echo "Error: Python 3 not found"
        exit 1
    fi

    if ! python3 -c "import fontTools" 2>/dev/null; then
        echo "Error: fonttools not installed"
        echo "Install with: pip install fonttools brotli"
        exit 1
    fi

    log_success "All dependencies found"
}

get_file_size() {
    local file=$1
    if [[ "$OSTYPE" == "darwin"* ]]; then
        stat -f%z "$file"
    else
        stat -c%s "$file"
    fi
}

format_size() {
    local bytes=$1
    if [ $bytes -lt 1024 ]; then
        echo "${bytes}B"
    else
        echo "$(( bytes / 1024 ))KB"
    fi
}

subset_font() {
    local input=$1
    local filename=$(basename "$input")
    local basename="${filename%.*}"
    local extension="${filename##*.}"

    log_info "Subsetting: $filename"

    # Get original size
    local original_size=$(get_file_size "$input")
    log_info "  Original size: $(format_size $original_size)"

    # Output file
    local output="$OUTPUT_DIR/${basename}-subset.woff2"

    # Subset the font
    pyftsubset "$input" \
        --output-file="$output" \
        --flavor=woff2 \
        --unicodes="$UNICODES" \
        --layout-features=* \
        --no-hinting \
        --desubroutinize \
        --name-IDs=* \
        --drop-tables= \
        --notdef-outline \
        --recommended-glyphs \
        --no-ignore-missing-unicodes

    # Calculate compression
    local output_size=$(get_file_size "$output")
    local reduction=$(( 100 - (output_size * 100 / original_size) ))

    log_success "  Subset created: ${basename}-subset.woff2"
    log_info "  Output size: $(format_size $output_size) (${reduction}% reduction)"
    echo ""
}

generate_font_css() {
    log_info "Generating font CSS..."

    local css_file="$OUTPUT_DIR/fonts.css"

    cat > "$css_file" << 'EOF'
/**
 * Bloom Website - Optimized Fonts
 * Generated by subset-fonts.sh
 */

/* Inter - Body Text */
@font-face {
  font-family: 'Inter';
  src: url('/fonts/inter-subset.woff2') format('woff2');
  font-weight: 400 700;
  font-display: swap;
  font-style: normal;
}

/* Orbitron - Headings (Sci-Fi Aesthetic) */
@font-face {
  font-family: 'Orbitron';
  src: url('/fonts/orbitron-subset.woff2') format('woff2');
  font-weight: 400 900;
  font-display: swap;
  font-style: normal;
}

/* Fallback font stack optimized for CLS prevention */
:root {
  --font-body: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  --font-heading: 'Orbitron', 'Impact', 'Arial Black', sans-serif;
}

body {
  font-family: var(--font-body);
}

h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
}
EOF

    log_success "Font CSS generated: $css_file"
}

download_fonts() {
    log_info "Downloading fonts (if needed)..."

    mkdir -p "$FONT_DIR"

    # Inter variable font
    if [ ! -f "$FONT_DIR/Inter-VariableFont.ttf" ]; then
        log_info "Downloading Inter..."
        curl -L "https://github.com/rsms/inter/releases/download/v3.19/Inter-3.19.zip" -o /tmp/inter.zip
        unzip -q /tmp/inter.zip "Inter Desktop/Inter-VariableFont_slnt,wght.ttf" -d /tmp/
        mv "/tmp/Inter Desktop/Inter-VariableFont_slnt,wght.ttf" "$FONT_DIR/Inter-VariableFont.ttf"
        rm -rf /tmp/inter.zip /tmp/Inter*
        log_success "Inter downloaded"
    fi

    # Orbitron
    if [ ! -f "$FONT_DIR/Orbitron-VariableFont.ttf" ]; then
        log_info "Downloading Orbitron..."
        curl -L "https://github.com/google/fonts/raw/main/ofl/orbitron/Orbitron%5Bwght%5D.ttf" -o "$FONT_DIR/Orbitron-VariableFont.ttf"
        log_success "Orbitron downloaded"
    fi
}

################################################################################
# Main Script
################################################################################

main() {
    log_info "====================================="
    log_info "Bloom Website Font Optimization"
    log_info "====================================="
    echo ""

    check_dependencies

    # Create output directory
    mkdir -p "$OUTPUT_DIR"

    # Download fonts if needed
    download_fonts

    # Check for fonts
    if [ ! -d "$FONT_DIR" ] || [ -z "$(ls -A $FONT_DIR/*.ttf 2>/dev/null)" ]; then
        log_warning "No font files found in $FONT_DIR"
        log_info "Place .ttf or .otf files in: $FONT_DIR"
        exit 0
    fi

    # Process fonts
    local processed=0
    for font in "$FONT_DIR"/*.ttf "$FONT_DIR"/*.otf; do
        [ -e "$font" ] || continue
        subset_font "$font"
        ((processed++))
    done

    # Generate CSS
    if [ $processed -gt 0 ]; then
        generate_font_css
    fi

    # Summary
    echo ""
    log_success "====================================="
    log_success "Font Optimization Complete!"
    log_success "====================================="
    log_info "Processed: $processed font(s)"
    log_info "Output: $OUTPUT_DIR"

    # Calculate total size
    local total_size=0
    for font in "$OUTPUT_DIR"/*.woff2; do
        [ -e "$font" ] || continue
        local size=$(get_file_size "$font")
        total_size=$((total_size + size))
    done

    log_info "Total font size: $(format_size $total_size)"

    if [ $total_size -lt 40960 ]; then
        log_success "Font budget met! (<40KB)"
    else
        log_warning "Font budget exceeded (>40KB)"
    fi

    echo ""
}

# Run main function
main "$@"
